version: '2'
services:
    codecept:
        image: codeception/codeception:2.4.5
        depends_on:
            - chrome
        volumes:
            - './tests:/project/tests'
            - './codeception.yml:/project/codeception.yml'
    chrome:
        image: 'selenium/standalone-chrome-debug:3.14'
        ports:
            - '5900:5900'
